### ISSUE TITLE
Latest changes seem toc rash on startup

### ISSUE THREAD

**Issue by NoxyNixie** [WesternGamer/FPSCounter#2]
```
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'AssemblyTitle' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (6,11)
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'AssemblyDescription' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (7,11)
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'AssemblyConfiguration' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (8,11)
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'AssemblyCompany' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (9,11)
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'AssemblyProduct' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (10,11)
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'AssemblyCopyright' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (11,11)
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'AssemblyTrademark' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (12,11)
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'AssemblyCulture' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (13,11)
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'ComVisible' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (18,11)
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'Guid' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (21,11)
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'AssemblyVersion' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (33,11)
2022-02-27 10:12:53.854 - Thread:   1 ->  [PluginLoader] CS0579: Duplicate 'AssemblyFileVersion' attribute in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Properties/AssemblyInfo.cs (34,11)
2022-02-27 10:12:53.855 - Thread:   1 ->  [PluginLoader] CS0101: The namespace 'FPSCounter' already contains a definition for 'FPSOverlay' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (13,19)
2022-02-27 10:12:53.855 - Thread:   1 ->  [PluginLoader] CS0101: The namespace 'FPSCounter' already contains a definition for 'Main' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Main.cs (10,17)
2022-02-27 10:12:53.855 - Thread:   1 ->  [PluginLoader] CS0234: The type or namespace name 'Utility' does not exist in the namespace 'Sandbox.Gui' (are you missing an assembly reference?) in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (6,18)
2022-02-27 10:12:53.855 - Thread:   1 ->  [PluginLoader] CS0246: The type or namespace name 'MEPluginLoader' could not be found (are you missing a using directive or an assembly reference?) in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/Main.cs (0,6)
2022-02-27 10:12:53.856 - Thread:   1 ->  [PluginLoader] CS0246: The type or namespace name 'IPlugin' could not be found (are you missing a using directive or an assembly reference?) in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/Main.cs (5,24)
2022-02-27 10:12:53.856 - Thread:   1 ->  [PluginLoader] CS0111: Type 'FPSOverlay' already defines a member called '.ctor' with the same parameter types in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (23,15)
2022-02-27 10:12:53.856 - Thread:   1 ->  [PluginLoader] CS0111: Type 'FPSOverlay' already defines a member called 'Draw' with the same parameter types in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (42,29)
2022-02-27 10:12:53.856 - Thread:   1 ->  [PluginLoader] CS0111: Type 'FPSOverlay' already defines a member called 'GetFriendlyName' with the same parameter types in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (57,31)
2022-02-27 10:12:53.856 - Thread:   1 ->  [PluginLoader] CS0111: Type 'FPSOverlay' already defines a member called 'UnloadData' with the same parameter types in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (62,29)
2022-02-27 10:12:53.856 - Thread:   1 ->  [PluginLoader] CS0111: Type 'FPSOverlay' already defines a member called 'Update' with the same parameter types in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (69,20)
2022-02-27 10:12:53.856 - Thread:   1 ->  [PluginLoader] CS0111: Type 'Main' already defines a member called 'Dispose' with the same parameter types in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Main.cs (22,20)
2022-02-27 10:12:53.856 - Thread:   1 ->  [PluginLoader] CS0111: Type 'Main' already defines a member called 'Update' with the same parameter types in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Main.cs (38,20)
2022-02-27 10:12:53.857 - Thread:   1 ->  [PluginLoader] CS0121: The call is ambiguous between the following methods or properties: 'FPSOverlay.FPSOverlay()' and 'FPSOverlay.FPSOverlay()' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/Main.cs (14,39)
2022-02-27 10:12:53.857 - Thread:   1 ->  [PluginLoader] CS0121: The call is ambiguous between the following methods or properties: 'Main.Dispose()' and 'Main.Dispose()' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Main.cs (25,21)
2022-02-27 10:12:53.857 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.Instance' and 'FPSOverlay.Instance' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (32,12)
2022-02-27 10:12:53.857 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.DataUpdateThread' and 'FPSOverlay.DataUpdateThread' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (33,12)
2022-02-27 10:12:53.857 - Thread:   1 ->  [PluginLoader] CS0121: The call is ambiguous between the following methods or properties: 'FPSOverlay.Update()' and 'FPSOverlay.Update()' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (33,58)
2022-02-27 10:12:53.857 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.DataUpdateThread' and 'FPSOverlay.DataUpdateThread' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (37,12)
2022-02-27 10:12:53.857 - Thread:   1 ->  [PluginLoader] CS0121: The call is ambiguous between the following methods or properties: 'FPSOverlay.FPSOverlay()' and 'FPSOverlay.FPSOverlay()' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/Main.cs (35,39)
2022-02-27 10:12:53.857 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.FPS' and 'FPSOverlay.FPS' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (46,57)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.SIMSpeed' and 'FPSOverlay.SIMSpeed' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (52,56)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.ServerSIMSpeed' and 'FPSOverlay.ServerSIMSpeed' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (58,63)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.DataUpdateThread' and 'FPSOverlay.DataUpdateThread' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (78,12)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.Instance' and 'FPSOverlay.Instance' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (79,12)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.FPS' and 'FPSOverlay.FPS' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (86,16)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.SIMSpeed' and 'FPSOverlay.SIMSpeed' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (87,16)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.ServerSIMSpeed' and 'FPSOverlay.ServerSIMSpeed' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/FPSOverlay.cs (91,20)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0103: The name 'm_grabInputFocus' does not exist in the current context in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (29,6)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.Instance' and 'FPSOverlay.Instance' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (34,12)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.DataUpdateThread' and 'FPSOverlay.DataUpdateThread' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (35,12)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0121: The call is ambiguous between the following methods or properties: 'FPSOverlay.Update()' and 'FPSOverlay.Update()' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (35,58)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.DataUpdateThread' and 'FPSOverlay.DataUpdateThread' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (39,12)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0103: The name 'MyFontHelper' does not exist in the current context in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (46,12)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0117: 'MyGuiConstants' does not contain a definition for 'DEFAULT_FONT' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (46,51)
2022-02-27 10:12:53.858 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.FPS' and 'FPSOverlay.FPS' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (46,73)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0103: The name 'MyFontHelper' does not exist in the current context in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (49,12)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0117: 'MyGuiConstants' does not contain a definition for 'DEFAULT_FONT' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (49,51)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.SIMSpeed' and 'FPSOverlay.SIMSpeed' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (49,72)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0103: The name 'MyFontHelper' does not exist in the current context in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (52,12)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0117: 'MyGuiConstants' does not contain a definition for 'DEFAULT_FONT' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (52,51)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.ServerSIMSpeed' and 'FPSOverlay.ServerSIMSpeed' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (52,79)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.DataUpdateThread' and 'FPSOverlay.DataUpdateThread' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (65,12)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.Instance' and 'FPSOverlay.Instance' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (66,12)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.FPS' and 'FPSOverlay.FPS' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (73,16)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.SIMSpeed' and 'FPSOverlay.SIMSpeed' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (74,16)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0103: The name 'MyPhysicsSandbox' does not exist in the current context in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (74,27)
2022-02-27 10:12:53.859 - Thread:   1 ->  [PluginLoader] CS0229: Ambiguity between 'FPSOverlay.ServerSIMSpeed' and 'FPSOverlay.ServerSIMSpeed' in file:
FPSCounter-47b04767f4189ce4e43c750aaad8d5edaf7dd702/MEVersion/FPSOverlay.cs (77,20)
2022-02-27 10:12:54.022 - Thread:   1 ->  [PluginLoader] Failed to load WesternGamer/FPSCounter|FPS Counter because of an error: System.Exception: Compilation failed!
   at avaness.PluginLoader.Compiler.RoslynCompiler.Compile(String assemblyName)
   at avaness.PluginLoader.Data.GitHubPlugin.CompileFromSource(Action`1 callback)
   at avaness.PluginLoader.Data.GitHubPlugin.GetAssembly()
   at avaness.PluginLoader.Data.PluginData.TryLoadAssembly(Assembly& a)
```

**Comment by WesternSpace** [comment]
I know what is happening, fixing shortly.
