### ISSUE TITLE
New crash on startup

### ISSUE THREAD

**Issue by NoxyNixie** [WesternGamer/FPSCounter#3]
```
2022-02-28 14:40:32.050 - Thread:   1 ->  [PluginLoader] Failed to initialize WesternGamer/FPSCounter|FPS Counter because of an error: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Noxy\AppData\Roaming\SpaceEngineers\Storage\PluginData\FPSCounter.cfg'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at FPSCounter.Config.PersistentConfig`1.Save(String path)
   at FPSCounter.Config.PersistentConfig`1.Load(PluginLogger log, String path)
   at FPSCounter.Main.Init(Object gameInstance)
   at avaness.PluginLoader.PluginInstance.Init(Object gameInstance)
```

Note: The folder `PluginData` doesn't even exist so for there to be a file `PluginData\FPSCounter.cfg` in there is impossible. 

Manually creating this folder does resolve this crash.

**Comment by WesternSpace** [comment]
Forgot that you need to create a folder for this to work, I already had a
folder for this on my computer which made me forget about it. Fix coming in
the next two hours.

**Comment by ForgetfulJones** [comment]
After unsub/resub/restart, I still had to create the folder manually.

```
2022-03-01 12:23:59.792 - Thread:   1 ->  [PluginLoader] Failed to initialize WesternGamer/FPSCounter|FPS Counter because of an error: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\User\AppData\Roaming\SpaceEngineers\Storage\PluginData\FPSCounter.cfg'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at FPSCounter.Config.PersistentConfig`1.Save(String path)
   at FPSCounter.Config.PersistentConfig`1.Load(PluginLogger log, String path)
   at FPSCounter.Main.Init(Object gameInstance)
   at avaness.PluginLoader.PluginInstance.Init(Object gameInstance)
2022-03-01 12:23:59.806 - Thread:  13 ->  Loading voxel storage from file 'C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\VoxelMaps\PirateBaseStaticAsteroid_A_5000m_2.vx2'```

**Comment by WesternSpace** [comment]
That is odd, will test and fix issue later when I have time. I have
something very important to attend to so I most likely won't be available
for the next week or most of the month.

**Comment by WesternSpace** [comment]
Issue has been fixed and verified to work, waiting on release of update.
