### ISSUE TITLE
Intermittent crash on startup, and on game close

### ISSUE THREAD

**Issue by kaedys** [WesternGamer/FPSCounter#6]
This crash _usually_ happens when I exit the game (preventing it from exiting cleanly), but I also encountered it twice while starting the game just now.  Appears that it's trying to set the title bar before the title bar actually exists yet, and isn't nil-checking it.

```
2024-06-27 12:13:40.246 - Thread:   1 ->  Plugin Init: avaness.PluginLoader.Main
2024-06-27 12:13:40.247 - Thread:   1 ->  [PluginLoader] [Info] Initializing 16 plugins
2024-06-27 12:13:40.265 - Thread:   1 ->  Info: Patched methods
2024-06-27 12:13:40.358 - Thread:  33 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at FPSCounter.GUI.TitlebarStats.UpdateTitleBar()
   at FPSCounter.GUI.TitlebarStats.Update()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2024-06-27 12:13:40.358 - Thread:  33 ->  Showing message
2024-06-27 12:13:40.358 - Thread:  33 ->  MyInitializer.OnCrash
2024-06-27 12:13:40.358 - Thread:  33 ->  var exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at FPSCounter.GUI.TitlebarStats.UpdateTitleBar()
   at FPSCounter.GUI.TitlebarStats.Update()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2024-06-27 12:13:42.786 - Thread:  33 ->  
================================== CRASH INFO ==================================
AppVersion: 01_204_018
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: False
ProcessRunTime: 14
PCUCount: 0
IsHang: False
GCMemory: 221
GCMemoryAllocated: 221
HWAvailableMemory: 31776
ProcessPrivateMemory: 1605
AnalyticId: SE
================================== OFNI HSARC ==================================
```

**Comment by WesternSpace** [comment]
Thanks for reporting the issue as well as attaching the error; will be fixing this in a hotfix.

**Comment by WesternSpace** [comment]
Resolved in https://github.com/WesternGamer/FPSCounter/commit/fd22554890451356f93bb7341c52b990238d93f3
